name: Deploy Resume to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload files to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name efrenresumelab \
          --destination '$web' \
          --source . \
          --overwrite
